# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

extends: default

rules:
  # These do not appear to be conventional in GitHub actions.
  document-end:
    present: false
  document-start:
    present: false
  # GitHub actions use "on" for triggers.
  truthy: disable
  # We have lots of long strings and command lines.
  line-length: disable
  comments:
    # Formatters may do this (e.g. Prettier does) and it seems like the most
    # trivial thing to get a failing check for.
    min-spaces-from-content: 1

ignore: /third_party/*
