name: DB Import

on:
  pull_request:
    paths:
      - devtools/db_import/**
  workflow_dispatch:

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on:
      # These tests need to run on GCE because the integration tests
      # access the GCS buckets which has to be authenticated with a
      # service account.
      - self-hosted  # must come first
      - runner-group=${{ github.event_name == 'pull_request' && 'presubmit' || 'postsubmit' }}
      - environment=prod
      - cpu
      - os-family=Linux
    env:
      DOCKER_IMAGE: gcr.io/iree-oss/openxla-benchmark/db_import@sha256:2c427286d467cdae7a206fdfe038bf32dbf9fbe68281866b571abeefe82907cd
    steps:
      - name: "Checking out PR repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791  # v2.5.0

      - name: Run unit tests
        id: run_unit_tests
        run: |
          docker run --rm -v $(pwd)/devtools/db_import:/work ${DOCKER_IMAGE} \
          python -m unittest discover -p \*_test.py -s /work/db_import -t db_import

      - name: Run integration tests
        id: run_integration_tests
        run: |
          docker run --rm -v $(pwd)/devtools/db_import:/work --pull=never ${DOCKER_IMAGE} \
          sh -c 'python /work/cli.py config list_pipelines | xargs python /work/cli.py verify'
