on:
  pull_request:

jobs:
  dummy:
    runs-on:
      - self-hosted  # must come first
      - runner-group=presubmit
      - environment=prod
      - gpu
      - os-family=Linux
    steps:
    - name: "Checking out PR repository"
      uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791  # v2.5.0
